chat アプリに合わせて templates を更新

diff --git a/django/templates/Makefile b/django/templates/Makefile
--- a/django/templates/Makefile
+++ b/django/templates/Makefile
@@ -4,22 +4,42 @@
 
 include .make_env
 
+precheck-docker:
+	@echo "IMAGE_NAME: $(IMAGE_NAME)"
+	@echo "CONTAINER_NAME: $(CONTAINER_NAME)"
+	@echo "DEV_PORT: $(DEV_PORT)"
+	@read -p "Is this correct? [Y/n]: " yn; \
+	case "$$yn" in \
+	  [Yy]* ) ;; \
+	  * ) echo "Aborting."; exit 1;; \
+	esac
+
+precheck-django:
+	@echo "APP_NAME: $(APP_NAME)"
+	@read -p "Is this correct? [Y/n]: " yn; \
+	case "$$yn" in \
+	  [Yy]* ) ;; \
+	  * ) echo "Aborting."; exit 1;; \
+	esac
+
 #===
 # 開発環境作成コマンド
 #===
 
 # dev
-build-dev:
+build-dev: precheck-docker
 	docker build -f Dockerfile.dev -t $(IMAGE_NAME)-dev .
 	-docker rm -f $(CONTAINER_NAME)-dev
-	docker run -p $(DEV_PORT):$(DEV_PORT) -v $$PWD:/app -d --name $(CONTAINER_NAME)-dev $(IMAGE_NAME)-dev tail -f /dev/null
+	docker run -p $(DEV_PORT):8000 -v $$PWD:/app -d --name $(CONTAINER_NAME)-dev $(IMAGE_NAME)-dev tail -f /dev/null
 
-create-app:
-	docker exec -it $(CONTAINER_NAME)-dev django-admin startproject $(PJ_NAME) .
+create-app: precheck-django
+	docker exec -it $(CONTAINER_NAME)-dev django-admin startproject config .
 	docker exec -it $(CONTAINER_NAME)-dev python manage.py startapp $(APP_NAME)
+	mkdir -p static/$(APP_NAME)
+	mkdir -p templates/$(APP_NAME)
 
 # migration ファイルの作成
-create-migration:
+create-migration: precheck-django
 	docker exec -it $(CONTAINER_NAME)-dev python manage.py makemigrations $(APP_NAME)
 
 # migration ファイルを用いてテーブルを作成
@@ -40,7 +60,7 @@ connect-python:
 
 # web サーバの起動
 run-server:
-	docker exec -it $(CONTAINER_NAME)-dev bash -c "python manage.py runserver 0.0.0.0:$(DEV_PORT)"
+	docker exec -it $(CONTAINER_NAME)-dev bash -c "python manage.py runserver 0.0.0.0:8000"
 
 start-dev:
 	docker start $(CONTAINER_NAME)-dev
@@ -60,7 +80,7 @@ run-test:
 	docker exec -it $(CONTAINER_NAME)-dev python manage.py test
 
 # prd
-build-server:
+build-server: precheck-docker
 	docker build -t $(IMAGE_NAME) .
 	-docker rm -f $(CONTAINER_NAME)
 	docker run -p 8000:8000 -d --name $(CONTAINER_NAME) $(IMAGE_NAME)
